"""
Azure Function: Trip Planner Agent
-----------------------------------
HTTP-triggered function that accepts trip parameters (origin, destination,
number of travellers, duration in days, budget level) and returns a
structured JSON travel plan generated by a Google Gemini model.

The Gemini model name and API key are configurable via environment
variables / Application Settings:

    GEMINI_API_KEY   - required. Your Google AI Studio / Gemini API key.
    GEMINI_MODEL     - optional. Defaults to "gemini-2.0-flash".
    GEMINI_API_BASE  - optional. Defaults to the public Generative
                        Language API base URL. Override if you proxy
                        requests or use a different API version.

Endpoint:
    POST /api/planTrip

Request body (JSON):
{
    "origin": "Auckland, New Zealand",
    "destination": "Tokyo, Japan",
    "travellers": 2,
    "duration_days": 7,
    "budget_level": "Mid-range"   // "Budget" | "Mid-range" | "Luxury"
}

Response body (JSON):
    Same shape as plan_response.json, e.g.

{
  "success": true,
  "data": {
    "destination": "...",
    "currency": "...",
    "summary": "...",
    "categories": [ ... ],
    "tips": [ ... ],
    "visaInfo": "...",
    "bestTimeToVisit": "..."
  }
}

On error, the response will be:

{
  "success": false,
  "error": "<human readable message>"
}
"""

import json
import logging
import os
import re

import azure.functions as func
import requests

app = func.FunctionApp(http_auth_level=func.AuthLevel.FUNCTION)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

DEFAULT_GEMINI_MODEL = "gemini-2.0-flash"
DEFAULT_GEMINI_API_BASE = "https://generativelanguage.googleapis.com/v1beta"

VALID_BUDGET_LEVELS = {"Budget", "Mid-range", "Luxury"}

# Categories that must always be present in the model's response, in this
# order. Used both to build the prompt and to validate the response.
REQUIRED_CATEGORY_IDS = [
    "flights",
    "accommodation",
    "food",
    "sightseeing",
    "transport",
    "misc",
]

CATEGORY_TEMPLATE = {
    "flights": {"icon": "✈️", "title": "Flights", "color": "#4a8fb5"},
    "accommodation": {"icon": "🏨", "title": "Accommodation", "color": "#2a7a6e"},
    "food": {"icon": "🍜", "title": "Food & Drink", "color": "#d4a843"},
    "sightseeing": {"icon": "🎯", "title": "Sightseeing & Activities", "color": "#c8522a"},
    "transport": {"icon": "🚗", "title": "Local Transport", "color": "#7a5a9e"},
    "misc": {"icon": "📦", "title": "Extras & Contingency", "color": "#5a9e6e"},
}

JSON_FENCE_RE = re.compile(r"^```(?:json)?\s*|\s*```$", re.IGNORECASE | re.MULTILINE)


# ---------------------------------------------------------------------------
# Input validation
# ---------------------------------------------------------------------------

class ValidationError(Exception):
    """Raised when the incoming request body fails validation."""

class UnauthorisedError(Exception):
    """Raised when the incoming request is not authorised."""


def parse_request_body(req: func.HttpRequest) -> dict:

    # Check incoming request header: x-apim-gateway-secret matches the environment variable APIM_GATEWAY_SECRET. 
    # This is set by the APIM policy to ensure that only requests from APIM reach this function.
    expected_secret = os.environ.get("APIM_GATEWAY_SECRET")
    if expected_secret:
        incoming_secret = req.headers.get("x-apim-gateway-secret")
        if incoming_secret != expected_secret:
            raise UnauthorisedError("Unauthorised: invalid or missing gateway secret.")

    try:
        body = req.get_json()
    except ValueError as exc:
        raise ValidationError("Request body must be valid JSON.") from exc

    if not isinstance(body, dict):
        raise ValidationError("Request body must be a JSON object.")

    origin = body.get("origin")
    destination = body.get("destination")
    travellers = body.get("travellers")
    duration_days = body.get("duration_days")
    budget_level = body.get("budget_level")

    if not origin or not isinstance(origin, str):
        raise ValidationError("'origin' is required and must be a non-empty string.")

    if not destination or not isinstance(destination, str):
        raise ValidationError("'destination' is required and must be a non-empty string.")

    if not isinstance(travellers, int) or travellers < 1:
        raise ValidationError("'travellers' is required and must be a positive integer.")

    if not isinstance(duration_days, int) or duration_days < 1:
        raise ValidationError("'duration_days' is required and must be a positive integer.")

    if budget_level not in VALID_BUDGET_LEVELS:
        raise ValidationError(
            "'budget_level' is required and must be one of: "
            + ", ".join(sorted(VALID_BUDGET_LEVELS))
        )

    return {
        "origin": origin.strip(),
        "destination": destination.strip(),
        "travellers": travellers,
        "duration_days": duration_days,
        "budget_level": budget_level,
    }


# ---------------------------------------------------------------------------
# Prompt construction
# ---------------------------------------------------------------------------

def build_prompt(params: dict) -> str:
    """Builds the prompt sent to Gemini, instructing it to return strictly
    formatted JSON matching the required schema."""

    schema_description = json.dumps(
        {
            "success": True,
            "data": {
                "destination": "string - destination city/country as provided",
                "currency": "string - 3-letter local currency code of the destination, e.g. JPY",
                "summary": "string - a one or two sentence evocative summary of the destination",
                "categories": [
                    {
                        "id": cat_id,
                        "icon": tmpl["icon"],
                        "title": tmpl["title"],
                        "subtitle": "string - short description of what this covers",
                        "color": tmpl["color"],
                        "totalCost": "number - total cost in NZD for ALL travellers combined",
                        "perPerson": "number - cost per person in NZD (totalCost / travellers)",
                        "lineItems": [
                            {"label": "string - short label", "value": "string - short value, may include $ amounts"}
                        ],
                    }
                    for cat_id, tmpl in CATEGORY_TEMPLATE.items()
                ],
                "tips": ["string - practical travel tip", "..."],
                "visaInfo": "string - visa requirements for a traveller from the given origin country",
                "bestTimeToVisit": "string - best time of year to visit and why",
            },
        },
        indent=2,
        ensure_ascii=False,
    )

    category_id_list = ", ".join(REQUIRED_CATEGORY_IDS)

    prompt = f"""You are a meticulous travel-planning assistant. Generate a detailed,
realistic trip cost breakdown and travel guide as a SINGLE valid JSON object
and nothing else (no markdown fences, no commentary, no explanations).

Trip details:
- Origin: {params['origin']}
- Destination: {params['destination']}
- Number of travellers: {params['travellers']}
- Trip duration: {params['duration_days']} day(s)
- Budget level: {params['budget_level']}

Requirements:
1. The output MUST be valid JSON matching exactly this structure and key
   names (the values below describe what each field should contain - replace
   them with real, realistic content for this specific trip):

{schema_description}

2. The "categories" array MUST contain exactly these 6 categories, in this
   order, using these exact "id", "icon", "title" and "color" values:
   {category_id_list}
3. All cost figures ("totalCost", "perPerson") must be numbers (not strings)
   representing approximate NZD amounts appropriate for the given budget
   level ({params['budget_level']}), number of travellers
   ({params['travellers']}), and duration ({params['duration_days']} days).
   "totalCost" is the combined cost for all travellers for the whole trip in
   that category; "perPerson" must equal totalCost divided by the number of
   travellers.
4. "lineItems" for each category should contain 3-4 short, useful,
   realistic facts relevant to that category (e.g. booking tips, must-try
   items, recommended areas, transport passes).
5. "tips" should contain 4-6 practical, destination-specific travel tips.
6. "visaInfo" must reflect the actual visa requirements for a citizen of the
   origin country ({params['origin']}) travelling to the destination
   ({params['destination']}).
7. "bestTimeToVisit" should be specific to the destination.
8. "currency" must be the correct ISO local currency code for the
   destination.
9. Do not include any text before or after the JSON object. Do not wrap the
   JSON in markdown code fences.
"""

    return prompt


# ---------------------------------------------------------------------------
# Gemini API call
# ---------------------------------------------------------------------------

def call_gemini(prompt: str) -> str:
    """Calls the Gemini generateContent endpoint and returns the raw text
    of the model's response."""

    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        raise RuntimeError("GEMINI_API_KEY environment variable is not set.")

    model = os.environ.get("GEMINI_MODEL", DEFAULT_GEMINI_MODEL)
    api_base = os.environ.get("GEMINI_API_BASE", DEFAULT_GEMINI_API_BASE)

    url = f"{api_base}/models/{model}:generateContent"

    payload = {
        "contents": [
            {
                "role": "user",
                "parts": [{"text": prompt}],
            }
        ],
        "generationConfig": {
            "temperature": 1.0,
            "responseMimeType": "application/json",
            "thinkingLevel" : "medium",
        },
    }

    headers = {
        "Content-Type": "application/json",
        "x-goog-api-key": api_key,
    }

    response = requests.post(url, headers=headers, json=payload, timeout=90)

    if response.status_code != 200:
        raise RuntimeError(
            f"Gemini API request failed with status {response.status_code}: "
            f"{response.text[:500]}"
        )

    body = response.json()

    try:
        candidates = body["candidates"]
        parts = candidates[0]["content"]["parts"]
        text = "".join(part.get("text", "") for part in parts)
    except (KeyError, IndexError, TypeError) as exc:
        raise RuntimeError(
            f"Unexpected Gemini API response shape: {json.dumps(body)[:500]}"
        ) from exc

    if not text.strip():
        raise RuntimeError("Gemini API returned an empty response.")

    return text


# ---------------------------------------------------------------------------
# Response parsing / validation
# ---------------------------------------------------------------------------

def extract_json(raw_text: str) -> dict:
    """Strips optional markdown code fences and parses the text as JSON."""

    cleaned = JSON_FENCE_RE.sub("", raw_text.strip()).strip()

    try:
        return json.loads(cleaned)
    except json.JSONDecodeError:
        pass

    # Fallback: try to locate the outermost JSON object in the text.
    start = cleaned.find("{")
    end = cleaned.rfind("}")
    if start != -1 and end != -1 and end > start:
        candidate = cleaned[start : end + 1]
        try:
            return json.loads(candidate)
        except json.JSONDecodeError as exc:
            raise RuntimeError(
                f"Failed to parse JSON from model response: {exc}"
            ) from exc

    raise RuntimeError("Model response did not contain valid JSON.")


def validate_plan(plan: dict) -> None:
    """Performs basic structural validation of the parsed plan. Raises
    RuntimeError if the structure is missing required fields."""

    if "data" not in plan or not isinstance(plan["data"], dict):
        raise RuntimeError("Parsed plan is missing a 'data' object.")

    data = plan["data"]

    required_top_level = [
        "destination",
        "currency",
        "summary",
        "categories",
        "tips",
        "visaInfo",
        "bestTimeToVisit",
    ]
    missing = [key for key in required_top_level if key not in data]
    if missing:
        raise RuntimeError(f"Plan 'data' is missing required field(s): {missing}")

    categories = data["categories"]
    if not isinstance(categories, list) or not categories:
        raise RuntimeError("Plan 'data.categories' must be a non-empty array.")

    category_ids = [cat.get("id") for cat in categories if isinstance(cat, dict)]
    missing_categories = [c for c in REQUIRED_CATEGORY_IDS if c not in category_ids]
    if missing_categories:
        raise RuntimeError(
            f"Plan 'data.categories' is missing required category id(s): "
            f"{missing_categories}"
        )

    for cat in categories:
        for field in ("totalCost", "perPerson", "lineItems"):
            if field not in cat:
                raise RuntimeError(
                    f"Category '{cat.get('id', '?')}' is missing field '{field}'."
                )


# ---------------------------------------------------------------------------
# HTTP trigger
# ---------------------------------------------------------------------------

@app.route(route="planTrip", methods=["POST"])
def plan_trip(req: func.HttpRequest) -> func.HttpResponse:
    logging.info("plan_trip: received request")

    try:
        params = parse_request_body(req)
    except UnauthorisedError as exc:
        return _json_response({"success": False, "error": str(exc)}, status_code=401)
    except ValidationError as exc:
        return _json_response({"success": False, "error": str(exc)}, status_code=400)

    prompt = build_prompt(params)

    try:
        raw_text = call_gemini(prompt)
        plan = extract_json(raw_text)
        validate_plan(plan)
    except RuntimeError as exc:
        logging.exception("plan_trip: failed to generate plan")
        return _json_response({"success": False, "error": str(exc)}, status_code=502)
    except Exception as exc:  # noqa: BLE001 - surface unexpected errors safely
        logging.exception("plan_trip: unexpected error")
        return _json_response(
            {"success": False, "error": f"Unexpected error: {exc}"}, status_code=500
        )

    # Ensure the top-level "success" flag is set correctly regardless of
    # what the model returned.
    plan["success"] = True

    return _json_response(plan, status_code=200)


def _json_response(payload: dict, status_code: int) -> func.HttpResponse:
    return func.HttpResponse(
        body=json.dumps(payload, ensure_ascii=False),
        status_code=status_code,
        mimetype="application/json",
    )
